### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by everamzah** [sofar/warps#1]
Hi.  I forked this baby but haven't made any changes yet.  As soon as I do, I'll try and figure out this PR business.  :)

Until then they are: The aforementioned "user quit the server so now I will crash" crash, which you know about.  However, this morning I discovered a second crashing bug, and that's when an admin /setwarp WarpNameWithA Space -- hence, you can create a warp with unusual characters in its name, and when you try to warp there it will crash (giving a nil on the x pos).

I'll try and patch these two up and send them your way.  :S

**Comment by sofar** [comment]
Thanks, closing this. If you find any new bugs, let me know!
